[tool.poetry]
name = "djx-cmds"
version = "0.2.2"
description = ""
authors = ["nope"]
readme = "README.md"
packages = [{ include = "djx_cmds" }]

[tool.poetry.dependencies]
python = "^3.10"
django = ">=4.1"
inflection = "^0.5.1"
jinja2 = "^3.1.2"
coreapi = "^2.3.3"
pyyaml = "^6.0.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[tool.poetry.group.dev.dependencies]
djangorestframework = "^3.15.2"
