[project]
name = "zuu"
version = "2.1.0"
description = "Zack's Useful Utilities"
authors = [
    { name = "ZackaryW", email = "gitzackw@gmail.com" }
]
dependencies = []
readme = "README.md"
requires-python = ">= 3.8"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = true
dev-dependencies = [
    "pillow>=10.4.0",
    "toml>=0.10.2",
    "pytest>=8.3.3",
    "pyyaml>=6.0.2",
]

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/zuu"]
