[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"



[project]
name = "MagneticReadoutProcessing"
version = "2.0.8"
description = "This library was created for the Low-Field MRI project and allows processing of data measured by magnetic field sensors. The focus is on visualization, followed by the provision of simple interfaces to work with this data. In general its possible to use this lib on all kinds of sensor data."
license = {file = "LICENSE"}
authors = [{name = "Marcel Ochsendorf", email = "info@marcelochsendorf.com"}]
dynamic = ["dependencies"]
requires-python = ">=3.7"
readme = {file = "README.md", content-type = "text/markdown"}
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent"
]

[project.scripts]
MRPCli = "MRPcli.cli:run"
MRPUdpp = "MRPudpp.udpp:run"
MRPUdppeditor = "MRPudppeditor.app:run"
MRPProxy = "MRPproxy.mrpproxy:run"

#[tool.setuptools.packages.find]
#where = ["pipelines", "readings", "static", "templates"]

[tool.setuptools]
include-package-data = true

[tool.setuptools.package-data]
"*" = ["**/*.mag.json", "**/*.yaml", "**/*.html", "**/*.js", "**/*.css", "**/*.md", "**/*.json", "**/*.ts", "**/*.xml"]

[project.urls]
"Homepage" = "https://github.com/LFB-MRI/MagneticReadoutProcessing"
"Bug Tracker" = "https://github.com/LFB-MRI/MagneticReadoutProcessing/issues"
"Documentation" = "https://magneticreadoutprocessing.readthedocs.io/en/latest/"

