[project]
name = "coordstometers"
version = "0.0.2"
authors = [{name="ThisTemba"}]
description = "Converts GPS coordinates to meters coordinates centered at some point and back"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/ThisTemba/coordstometers"
Issues = "https://github.com/ThisTemba/coordstometers/issues"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"