[tool.poetry]
name = "pytest-clerk"
version = "3.0.0"
description = "A set of pytest fixtures to help with integration testing with Clerk."
authors = ["Ryan Causey <ryan.causey@munipal.io>"]
license = "MIT"
readme = "README.md"
repository = "https://gitlab.com/munipal-oss/pytest-clerk"
homepage = "https://gitlab.com/munipal-oss/pytest-clerk"
packages = [{include = "pytest_clerk"}]
classifiers = ["Framework :: Pytest"]

[tool.poetry.dependencies]
python = "^3.10"
pytest = "^8.0.0"
python-decouple = "^3.0"
tenacity = "^9.0.0"
httpx = "^0.27.0"
pytest-aws-fixtures = {version = "^2.0.0", optional = true}

[tool.poetry.group.dev.dependencies]
prospector = "^1.10.2"
black = "^24.0.0"
isort = "^5.12.0"
pre-commit = "^4.0.0"

[tool.poetry.extras]
aws = ["pytest-aws-fixtures"]

[tool.poetry.plugins."pytest11"]
pytest_clerk = "pytest_clerk.clerk"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
