[tool.poetry]
name        = "osbot_serverless_flows"
version     = "v0.7.28"
description = "OSBot Serverless Flows"
authors     = ["Dinis Cruz <dinis.cruz@owasp.org>"]
license     = "MIT"
readme      = "README.md"
homepage    = "https://github.com/owasp-sbot/OSBot-Serverless-Flows"
repository  = "https://github.com/owasp-sbot/OSBot-Serverless-Flows"

[tool.poetry.dependencies]
python           = "^3.11"
osbot-utils      = "*"
osbot-aws        = "*"
osbot-fast-api   = "*"
mangum           = "*"
requests         = "*"
httpx            = "*"
osbot_playwright = "*"
bs4              = "*"

[build-system]
requires        = ["poetry-core>=1.0.0"]
build-backend   = "poetry.core.masonry.api"

# poetry export -f requirements.txt --without-hashes > requirements.txt
