[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "cdef-utils"
version = "2.5.0"
description = "Utility for converting CSV to Parquet files"
authors = [{ name = "Tobias Kragholm", email = "tkragholm@gmail.com" }]
requires-python = ">=3.9"
readme = "README.md"
license = "MIT"
keywords = ["csv", "parquet", "data processing"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]
dependencies = ["polars", "rich", "pyarrow"]

[project.scripts]
cdef-convert = "cdef_utils.convert:run_convert"

[project.urls]
Homepage = "https://github.com/tkragholm/cdef-utils"
"Bug Tracker" = "https://github.com/tkragholm/cdef-utils/issues"


[tool.hatch.build.targets.wheel]
packages = ["cdef_utils"]


[tool.ruff]
line-length = 88
target-version = "py312"

[tool.ruff.lint]
select = ["E", "F", "I"]
