[project]
name = "cdef-utils"
version = "2.0.0"
description = "Utility for converting CSV to Parquet files"
authors = ["Tobias Kragholm <tkragholm@gmail.com>"]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-64", "osx-arm64", "win-64"]

[dependencies]
python = ">=3.9"
polars = "*"
rich = "*"
hatch = "*"
pytest = "*"
ruff = "*"
twine = "*"
chardet = "*"

[tasks]
start = "python -m cdef_utils.00_convert"
test = "pytest tests"
format = "ruff format"
build = { cmd = "hatch build", depends_on = ["format"] }
publish = { cmd = "twine upload dist/*", depends_on = ["build"] }
