[project]
name = "illallangi-django-swimming"
authors = [
    { name = "Andrew Cole", email = "andrew.cole@illallangi.com" }
]
maintainers = [
    { name = "Andrew Cole", email = "andrew.cole@illallangi.com" }
]
description = "A Django application for recording swimming workouts."
readme = "README.md"
requires-python = ">=3.10.1"
dependencies = [
    "diffsync>=2.0.0",
    "django-htmx>=1.19.0",
    "django-sqids>=0.2.0",
    "django>=5.1.1",
    "illallangi-mastodon>=0.2.0",
]
keywords = [
    "django",
    "swimming",
]
version = "0.1.1"
classifiers =[
  "Development Status :: 3 - Alpha",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Python :: 3.12",
]
license = { text = "MIT License" }
[project.urls]
Homepage = "https://github.com/illallangi/django-swimming"
Repository = "https://github.com/illallangi/django-swimming.git"
Issues = "https://github.com/illallangi/django-swimming/issues"
Changelog = "https://github.com/illallangi/django-swimming/blob/master/CHANGELOG.md"
[build-system]
requires = [
    "ruff>=0.6.9",
    "hatchling>=1.25.0",
]
build-backend = "hatchling.build"
[tool.djlint]
profile="django"
format_css=true
format_js=true
ignore="H006"
[tool.ruff]
lint.select = ["ALL"]
lint.ignore = [
    "COM812",
    "E501",
    "ISC001",
]
exclude = [
    "**/migrations/0*.py",
]
[tool.ruff.lint.pydocstyle]
convention = "pep257"
[tool.uv]
dev-dependencies = [
    "ruff>=0.6.9",
    "hatchling>=1.25.0",
    "commitizen>=3.29.1",
    "pre-commit>=3.8.0",
    "django_createsuperuserwithpassword>=2.0.0",
    "djlint>=1.35.2",
]
[tool.hatch.build.targets.sdist]
exclude = [
    "Makefile",
    "manage.py",
    "src/home/*",
    "src/manage.py",
    "src/myserver/*",
    "uv.lock",
]
[tool.hatch.build.targets.wheel]
packages = ["src/illallangi"]
exclude = [
    "Makefile",
    "manage.py",
    "src/home/*",
    "src/manage.py",
    "src/myserver/*",
    "uv.lock",
]
[tool.commitizen]
name = "cz_conventional_commits"
version_provider = "pep621"
tag_format = "v$version"
version_files = [
    "pyproject.toml:version",
    "src/illallangi/django/swimming/__version__.py:__version__",
]
update_changelog_on_bump = true
major_version_zero = true
