[project]
name = "gyjd"
version = "0.1.0dev7"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = []

[project.scripts]
gyjd = "gyjd.__main__:main"

[project.optional-dependencies]
compiler = ["nuitka"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"


[tool.hatch.build.targets.wheel]
packages = ["src/gyjd"]

[tool.hatch.build]
exclude = ["/tests", "/docs"]

[tool.hatch.envs.hatch-test]
dependencies = ["pytest >=8.3.3,<9"]
extra-args = ["-vv"]

[tool.hatch.envs.hatch-test.scripts]
run = "pytest{env:HATCH_TEST_ARGS:} {args}"

[tool.uv]
dev-dependencies = ["pytest >=8.3.3,<9"]

[tool.pytest.ini_options]
pythonpath = "src"
testpaths = ["tests"]
