[tool.poetry]
name = "stock-stil"
version = "0.1.6"
description = "stock是一个股票数据采集库，目前支持采集股票论坛的评论数据"
authors = ["科技创新实验室 <swszLab@163.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.7"
requests = "^2.32.3"
beautifulsoup4="^4.12.3"
lxml="^5.3.0"
tqdm="^4.66.5"
wget="^3.2"
pandas="^2.2.2"
aiohttp="^3.10.5"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[project.urls]
Homepage="https://gitee.com/hbue_stil/stock_stil"
