[tool.poetry]
name = "latexcor"
version = "0.1.17"
description = "latex automation"
license = "MIT"
authors = ["David Couronn√© <couronne.david@gmail.com>"]
readme = "README.md"
homepage = "https://github.com/infocornouaille/latexcor"
repository = "https://github.com/infocornouaille/latexcor"
keywords = ["latex", "jupyter", "notebook"]

[tool.poetry.dependencies]
python = "^3.8"
chardet = "^5.1.0"
python-slugify = "^8.0.1"


[tool.poetry.scripts]
latexcor= 'latexcor.cli:main'

[tool.poetry.group.dev.dependencies]
jupytercor = "^0.1.10"
black = "^23.1.0"
jupyterlab-black = "^0.2.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
