[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "prepCV"
version = "1.0.0"
description = "Define preprocessing pipelines using nested callable functions and parameter grids for them."
authors = [{ name = "Kalmy8" }]
license = { file = "LICENSE" }
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License"]
requires-python = "~=3.9"

[tool.black]
line-length = 99
include = '\.pyi?$'
exclude = '''\.git|\.venv'''

[tool.ruff.lint.isort]
known_first_party = ["prepCV"]
force_sort_within_sections = true

[tool.isort]
profile = "black"
line_length = 94
multi_line_output = 3
skip_gitignore = true
skip_glob = ["**/migrations/*", "**/settings/*"]
src_paths = ["./prepCV"]

[tool.mypy]
files = "prepCV"
exclude = "__init__.py"
check_untyped_defs = true
disallow_any_generics = true
ignore_missing_imports = true
no_implicit_optional = true
show_error_codes = true
strict_equality = true
warn_redundant_casts = true
warn_return_any = true
warn_unreachable = true
warn_unused_configs = true
no_implicit_reexport = true


[tool.flake8]
max-line-length = 94
extend-ignore = ["E501", "E203", "W503"]
per-file-ignores = ["settings*.py:E402,F403,F405"]
include = '\.py$'
exclude = [
  ".git",
  "__pycache__",
  ".tox",
  ".eggs",
  "*.egg",
  ".venv",
  "*.toml",
  "__init__.py",
  "setup.py",
  "tasks.py"]

[tool.commitizen]
name = "cz_conventional_commits"
version = "1.0.0"
tag_format = "v{major}.{minor}.{patch}"
