[project]
name = "cdef-utils"
version = "2.4.1"
description = "Utility for converting CSV to Parquet files"
authors = ["Tobias Kragholm <tkragholm@gmail.com>"]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-64", "osx-arm64", "win-64"]

[dependencies]
python = ">=3.9"
polars = "*"
rich = "*"
hatch = "*"
ruff = "*"
twine = "*"
pyarrow = ">=17.0.0,<18"
ujson = ">=5.10.0,<6"

[tasks]
format = "ruff format"
build = { cmd = "hatch build", depends_on = ["format"] }
publish = { cmd = "twine upload dist/*", depends_on = ["build"] }

[pypi-dependencies]
charset-normalizer = { version = "*", extras = ["unicode-backport"] }
