[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "PyMoot"
version = "1.1.3"
description = "Python wrapper for Komoot APIs"
authors = [
    { name = "FlorÃ©al Cabanettes", email = "contacter@alypie.fr" },
]
readme = "README.md"
requires-python = ">=3.11"
license = {text = "GPLv3"}
keywords = ["komoot", "api", "python"]
dependencies = [
    "dateutils>=0.6.12",
    "python-dateutil>=2.8.2",
    "requests>=2.31.0",
    "pillow>=10.1.0",
    "gpxpy>=1.6.1",
    "fit_tool>=0.9.13",
]

[project.urls]
homepage = "https://gite.alypie.fr/veloroots/pymoot"
repository = "https://gite.alypie.fr/veloroots/pymoot"

[tool.setuptools.packages.find]
where = ["src"]
