[project]
name = "polarcle"
version = "0.2.1"
description = "Polars Dataframe integration with Oracle"
authors = [{ name = "iwolf", email = "isaacwolfsite@gmail.com" }]
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["polars", "oracledb"]


[tool.uv]
dev-dependencies = ["ruff"]


[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
